# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#apache-maven-with-a-settings-path

name: Build

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Build'
        required: true
        default: 'Build'
      home:
        description: 'location'
        required: false

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      with:
        java-version: 1.8
      uses: actions/setup-java@v1

    - name: Build with Maven
      run: mvn -B -U package -T 2C

    - name: Archive artifacts (JAR)
      uses: actions/upload-artifact@v2
      if: success()
      with:
          name: AntiCheatReloaded
          path: target/AntiCheatReloaded.jar
